---
name: Build

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  library:
    name: Library
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: TheHackerApp/setup-rust@main
        with:
          ssh-private-key: ${{ secrets.SHIPYARD_SSH_KEY }}
          token: ${{ secrets.SHIPYARD_TOKEN }}

      - run: cargo build --release --lib

  binary:
    name: Binary
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: TheHackerApp/setup-rust@main
        with:
          ssh-private-key: ${{ secrets.SHIPYARD_SSH_KEY }}
          token: ${{ secrets.SHIPYARD_TOKEN }}

      - run: cargo build --release --bin migrate -F cli

      - uses: actions/upload-artifact@v4
        with:
          name: migrate
          path: target/release/migrate
