---
name: Lint

on:  # yamllint disable-line rule:truthy
  - push

jobs:
  yaml:
    name: YAML
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: pip install yamllint
      - run: yamllint -s -f github .

  style:
    name: Style
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: TheHackerApp/setup-rust@main
        with:
          components: rustfmt
          ssh-private-key: ${{ secrets.SHIPYARD_SSH_KEY }}
          token: ${{ secrets.SHIPYARD_TOKEN }}

      - run: cargo fmt --all --check

  clippy:
    name: Clippy
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: TheHackerApp/setup-rust@main
        with:
          components: clippy
          ssh-private-key: ${{ secrets.SHIPYARD_SSH_KEY }}
          token: ${{ secrets.SHIPYARD_TOKEN }}

      - run: cargo clippy --all-features -- -D warnings
